# Generated by Django 4.1 on 2022-08-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_tweet_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='time',
        ),
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(default='2022-08-09T11:14:17.000Z'),
            preserve_default=False,
        ),
    ]
