# Generated by Django 4.1 on 2022-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_tweet_date_remove_tweet_time_tweet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_state',
            field=models.CharField(default='NA', max_length=36),
            preserve_default=False,
        ),
    ]
