# Generated by Django 4.1 on 2022-08-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_tweet_tweet_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='disaster_type',
            field=models.CharField(default='flood', max_length=48),
            preserve_default=False,
        ),
    ]
