name: CI to Docker Hub
on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

steps:

  - name: Check out Repo
    uses: actions/checkout@v2

  - name: Login to Docker Hub
    uses: docker/login-action@v1
    with:
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  - name: Set up Docker Buildx
    id: docker_build
    uses: docker/setup-buildx-action@v1

  - name: Build and push
    id: docker_build
    uses: docker/build-push-action@v2
    with:
      context: ./frontend/
      file: ./frontend/Dockerfile
      builder: ${{ steps.buildx.outputs.name }}
      push: true
      tags:  ${{ secrets.DOCKER_HUB_USERNAME }}/disasteropedia-frontend:latest
      cache-from: type=local,src=/frontend/tmp/.buildx-cache
      cache-to: type=local,dest=/frontend/tmp/.buildx-cache

  - name: Image digest
    run: echo ${{ steps.docker_build.outputs.digest }}

  - name: Cache Docker layers
    uses: actions/cache@v2
    with:
      path: /frontend/tmp/.buildx-cache
      key: ${{ runner.os }}-buildx-${{ github.sha }}
      restore-keys: |
        ${{ runner.os }}-buildx-
